name: Build with PyInstaller

on:
  push:
    branches:
      - release

jobs:
  pyinstaller-build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install PyInstaller
      run: pip install pyinstaller
    
    - name: Build with PyInstaller
      run: pyinstaller bethini_onefile.spec
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Bethini
        path: dist/Bethini
