name: Build with PyInstaller

on:
  push:
    branches:
      - release

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: PyInstaller Action
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.11'
          spec: bethini_onefile.spec
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Bethini'
          
  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip -install --upgrade pip
          pip install -r requirements.txt
        
      - name: PyInstaller Action
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.11'
          spec: bethini_onefile.spec
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Bethini'

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
