name: Build with PyInstaller

on:
  push:
    branches:
      - release

jobs:
  pyinstaller-build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    
    - name: Setup Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.11.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install PyInstaller
      run: pip install pyinstaller
    
    - name: Build with PyInstaller
      run: pyinstaller bethini_onefile.spec
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Bethini-linux
        path: dist
        
  pyinstaller-build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    
    - name: Setup Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.11.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install PyInstaller
      run: pip install pyinstaller
    
    - name: Build with PyInstaller
      run: pyinstaller bethini_onefile.spec

    - name: Copy additional files
      run: |
        copy LICENSE.txt dist\LICENSE.txt
        copy README.md dist\README.md
        copy changelog.txt dist\changelog.txt
        mkdir dist\icons
        xcopy /e /i icons dist\icons
        mkdir dist\fonts\Comfortaa
        xcopy /e /i fonts\Comfortaa dist\fonts\Comfortaa
        mkdir dist\apps
        mkdir "dist\apps\Fallout 4"
        xcopy /y "apps\Fallout 4\Bethini.json" "dist\apps\Fallout 4\"
        xcopy "apps\Fallout 4\settings.json" "dist\apps\Fallout 4\"
        mkdir "dist\apps\Fallout New Vegas"
        xcopy /y "apps\Fallout New Vegas\Bethini.json" "dist\apps\Fallout New Vegas\"
        xcopy /y "apps\Fallout New Vegas\settings.json" "dist\apps\Fallout New Vegas\"
        mkdir "dist\apps\Fallout New Vegas\images"
        xcopy /e /i "apps\Fallout New Vegas\images" "dist\apps\Fallout New Vegas\images"
        rmdir /s /q "dist\Bethini\apps\Fallout New Vegas\images\src"
        mkdir "dist\apps\Skyrim Special Edition"
        xcopy /y "apps\Skyrim Special Edition\Bethini.json" "dist\apps\Skyrim Special Edition\"
        xcopy /y "apps\Skyrim Special Edition\settings.json" "dist\apps\Skyrim Special Edition\"
        mkdir "dist\apps\Skyrim Special Edition\images"
        xcopy /e /i "apps\Skyrim Special Edition\images" "dist\apps\Skyrim Special Edition\images"
        rmdir /s /q "dist\Bethini\apps\Skyrim Special Edition\images\src"
        mkdir "dist\apps\Starfield"
        xcopy /y "apps\Starfield\Bethini.json" "dist\apps\Starfield\"
        xcopy /y "apps\Starfield\settings.json" "dist\apps\Starfield\"
        mkdir "dist\apps\Starfield\images"
        xcopy /e /i "apps\Starfield\images" "dist\apps\Starfield\images"
        rmdir /s /q "dist\Bethini\apps\Starfield\images\src"
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Bethini-windows
        path: dist
