name: Build with PyInstaller

on:
  push:
    branches:
      - release

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: PyInstaller Action
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.11'
          spec: bethini_onefile.spec
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Bethini'
  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: PyInstaller Action
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.11'
          spec: bethini_onefile.spec
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Bethini'
