name: Build with PyInstaller

on:
  push:
    branches:
      - release

jobs:
  pyinstaller-build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    
    - name: Setup Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install PyInstaller
      run: pip install pyinstaller
    
    - name: Build with PyInstaller
      run: pyinstaller bethini_onefile.spec
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Bethini
        path: dist/Bethini
