name: Build with PyInstaller

on:
  push:
    branches:
      - release

jobs:
  pyinstaller-build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    
    - name: Setup Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.11.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install PyInstaller
      run: pip install pyinstaller
    
    - name: Build with PyInstaller
      run: pyinstaller bethini_onefile.spec
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Bethini-linux
        path: dist
        
  pyinstaller-build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    
    - name: Setup Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.11.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install PyInstaller
      run: pip install pyinstaller
    
    - name: Build with PyInstaller
      run: pyinstaller bethini_onefile.spec

    - name: List files in dist
      run: |
        echo "Listing files in apps directory:"
        dir apps

    - name: Copy additional files
      run: |
        copy LICENSE.txt dist\LICENSE.txt
        copy README.md dist\README.md
        copy changelog.txt dist\changelog.txt
        mkdir dist\icons
        xcopy /e /i icons dist\icons
        mkdir dist\fonts\Comfortaa
        xcopy /e /i fonts\Comfortaa dist\fonts\Comfortaa
        mkdir dist\apps
        #This had better work...
        $workspace = $Env:GITHUB_WORKSPACE
        Copy-Item "$workspace\apps\Starfield\Bethini.json" "$workspace\dist\apps\Starfield\Bethini.json" -Force -ErrorAction SilentlyContinue
        Copy-Item "$workspace\apps\Starfield\settings.json" "$workspace\dist\apps\Starfield\settings.json" -Force -ErrorAction SilentlyContinue
        Copy-Item "$workspace\apps\Starfield\images" "$workspace\dist\apps\Starfield\images" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force "$workspace\dist\apps\Starfield\images\src" -ErrorAction SilentlyContinue
        Copy-Item "$workspace\apps\Fallout 4\Bethini.json" "$workspace\dist\apps\Fallout 4\Bethini.json" -Force -ErrorAction SilentlyContinue
        Copy-Item "$workspace\apps\Fallout 4\settings.json" "$workspace\dist\apps\Fallout 4\settings.json" -Force -ErrorAction SilentlyContinue
        Copy-Item "$workspace\apps\Fallout New Vegas\Bethini.json" "$workspace\dist\apps\Fallout New Vegas\Bethini.json" -Force -ErrorAction SilentlyContinue
        Copy-Item "$workspace\apps\Fallout New Vegas\settings.json" "$workspace\dist\apps\Fallout New Vegas\settings.json" -Force -ErrorAction SilentlyContinue
        Copy-Item "$workspace\apps\Fallout New Vegas\images" "$workspace\dist\apps\Fallout New Vegas\images" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force "$workspace\dist\apps\Fallout New Vegas\images\src" -ErrorAction SilentlyContinue
        Copy-Item "$workspace\apps\Skyrim Special Edition\Bethini.json" "$workspace\dist\apps\Skyrim Special Edition\Bethini.json" -Force -ErrorAction SilentlyContinue
        Copy-Item "$workspace\apps\Skyrim Special Edition\settings.json" "$workspace\dist\apps\Skyrim Special Edition\settings.json" -Force -ErrorAction SilentlyContinue
        Copy-Item "$workspace\apps\Skyrim Special Edition\images" "$workspace\dist\apps\Skyrim Special Edition\images" -Recurse -Force -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force "$workspace\dist\apps\Skyrim Special Edition\images\src" -ErrorAction SilentlyContinue
        
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Bethini-windows
        path: dist
